# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { 'postgres://42tools-api:wEiTu52FdB86@127.0.0.1/42tools-api_development' } %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { 'postgres://42tools-api:wEiTu52FdB86@127.0.0.1/42tools-api_test' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
